
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: nginx-chaos
  namespace: default
spec:
  # It can be active/stop
  engineState: 'active'
  appinfo:
    appns: ''
    applabel: ''
    appkind: ''
  chaosServiceAccount: pod-cpu-hog-sa
  experiments:
    - name: pod-cpu-hog
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: '60' # in seconds

            - name: CPU_CORES
              value: '1'    

            ## Percentage of total pods to target
            - name: PODS_AFFECTED_PERC
              value: ''   

            ## provide the cluster runtime
            - name: CONTAINER_RUNTIME
              value: 'containerd'        

            # provide the socket file path
            - name: SOCKET_PATH
              value: '/run/containerd/containerd.sock'
        probe:
          - name: healthcheck
            type: cmdProbe
            mode: Edge
            runProperties:
              probeTimeout: 180
              retry: 0
              interval: 1
              stopOnFailure: true
            cmdProbe/inputs:
              command: ./healthcheck -name pod-level
              source:
                image: chaosnative/go-runner:3.0.1-saas
                inheritInputs: true
              comparator:
                type: string
                criteria: contains
                value: "[P000]"    
